### ISSUE TITLE
Name of package for installing is written wrong on website

### ISSUE THREAD

**Issue by ANIBIT14** [graysonw/target-bigquery#13]
The package target to be installed is pip install target-bigquery but on https://www.singer.io/tap/postgresql/google-bigquery/ it is mentioned pip install targert-google-bigquery

Please correct it.

**Comment by paddie** [comment]
There's a chance that realself aren't actually responsible for the singer.io page you are referring to.

**Comment by ANIBIT14** [comment]
> There's a chance that realself isn't actually responsible for the singer.io Page you are referring to.

I am closing the issue because what is said above may be true, though the problem has not been fixed.
